Started by user [8mha:////4AaLTPvsSlus8agwzA8REbkPHt6pe+gFNQjHhXi0JLw4AAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzuEgZe/dLi1CL95IzMvNzESgC1+YY6wgAAAA==[0mChinmay Jog
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/workspace/Admin_Tools/Configure_Web_Server
[Configure_Web_Server] $ /bin/sh -xe /tmp/jenkins14728590320088922884.sh
+ sudo ansible-playbook /data/ansibleansible/playbooks/server_web_configuration.yml

PLAY [Configure newly added webserver] *****************************************

TASK [Gathering Facts] *********************************************************
[WARNING]: Platform linux on host web1 is using the discovered Python
interpreter at /usr/bin/python3.12, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.17/reference_appendices/interpreter_discovery.html for more information.
[WARNING]: Platform linux on host web2 is using the discovered Python
interpreter at /usr/bin/python3.12, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.17/reference_appendices/interpreter_discovery.html for more information.
ok: [web1]
ok: [web2]

TASK [Update all packages] *****************************************************
ok: [web1]
changed: [web2]

TASK [Install basic packages] **************************************************
ok: [web1]
ok: [web2]

TASK [Enable necessary Apache2 modules] ****************************************
changed: [web2]
changed: [web1]

TASK [Settting apache2 directories] ********************************************
ok: [web2] => (item=auth-available)
ok: [web1] => (item=auth-available)
ok: [web2] => (item=auth-enabled)
ok: [web1] => (item=auth-enabled)

TASK [Settting apache2 IncludeOptional] ****************************************
ok: [web1] => (item=auth-enabled)
ok: [web2] => (item=auth-enabled)

TASK [Setting up web_users group] **********************************************
ok: [web1]
ok: [web2]

TASK [Adding www-data to web_users group] **************************************
ok: [web2]
ok: [web1]

TASK [Setting GID on /websites directory] **************************************
ok: [web2]
ok: [web1]

TASK [Adding default index package] ********************************************
ok: [web2]
ok: [web1]

TASK [Adding default apache2 conf] *********************************************
ok: [web1]
ok: [web2]

TASK [Starting apache2 service] ************************************************
ok: [web1]
ok: [web2]

TASK [Add the main PPA for supported PHP versions] *****************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:  != , E:The list of sources could not be read.
fatal: [web2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.0.0.4 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/data/ansible.ansible/tmp/ansible-tmp-1738146630.1068456-23339-67947248740646/AnsiballZ_apt_repository.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/data/ansible.ansible/tmp/ansible-tmp-1738146630.1068456-23339-67947248740646/AnsiballZ_apt_repository.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/data/ansible.ansible/tmp/ansible-tmp-1738146630.1068456-23339-67947248740646/AnsiballZ_apt_repository.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.apt_repository', init_globals=dict(_module_fqn='ansible.modules.apt_repository', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_0c5rel9s/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 773, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.apt_repository_payload_0c5rel9s/ansible_ansible.builtin.apt_repository_payload.zip/ansible/modules/apt_repository.py\", line 750, in main\r\n  File \"/usr/lib/python3/dist-packages/apt/cache.py\", line 157, in __init__\r\n    self.open(progress)\r\n  File \"/usr/lib/python3/dist-packages/apt/cache.py\", line 214, in open\r\n    self._cache = apt_pkg.Cache(progress)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^\r\napt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ noble: -----BEGIN PGP PUBLIC KEY BLOCK-----\r\n\r\nmQINBGYo0vEBEAC0Semxy5I2b8exRUxJfTKkHR4f5uyS0dTd9vYgMI5T3gsa7ypH\r\nHtE+GiZC+T9m/F9h66+XJMxhuNsKRs7T2In5NSeso9H/ytlSTayUaBtCFfRp6y6b\r\n6ozuRBfqYJGxhjAnIzvNF/Wpp2BvfQm3OrQ7uJJrt5IvzLDC4jPxl/Xs3sTT+Hbk\r\nbkKKprZ3xmy2enuwBaNWR/CUtAz3hbkzL1kGbhX9m3QidFJagVVdDw3aNEwo8ush\r\ndjWfF+BajNvpDFYJKBGQbCeagB753Baa5yIN62x+THLnLiKTMDS1e7U0ZDiV9671\r\nnoTbtN5TeZeyfsEmeZ8X60x11JIP3yYHYZT70/DyTYX3WC9yQFyIgVOfRlGklMKI\r\nk3TLMmtq8w5Hz1vovwzV7PzaQnmY+uNP2ZbAP4fJ3iFAj0L+u0i1nOFgTy0Lq058\r\nO/FjRrQxuceDDCF+9ThspXMw3Puvz8giuBDCdEda84uC7XWMdqgz/maLfFQjAmyP\r\nIxi1EMxMlHYyZajpR1cdCfrAIQlnQjHSWmyeCFgXPPfRA71aCcJ7oSrDjogW6Ahd\r\nHRkQRKf1FF9BFzycgSQotfR+7CKfPQh1kghufM9W/spARzA709nGZjXJzgEJLQd3\r\nCDB6dIIxT/0YI36h3Qgfmiiw4twO24MMEqEEPIELz2WJKeWGkdQdcekpxQARAQAB\r\ntB9MYXVuY2hwYWQgUFBBIGZvciBPbmTFmWVqIFN1csO9iQJOBBMBCgA4FiEEuNx+\r\nU5RmVu+85MHdcdrqq0rUyrYFAmYo0vECGwMFCwkIBwIGFQoJCAsCBBYCAwECHgEC\r\nF4AACgkQcdrqq0rUyrYOPQ/+IArA4s1J3op/w7cXek0ieFHWHFDrxPYS+78/LF/J\r\nLoYZw0nIU5Ovr+LzehFMIQU6esgPXwbeCVgwLwat57augAkAYWT0UzH5dE6RKAGr\r\nC2vsHWVfPhQn6UndfzwXc0mTLGQni25aQaZ6k60Dbm/vblejrTQrtAUWoMO3Z1cr\r\nNDGJ3Z9DCxtr2o9gRYUI6HwLHJtobTIeI5xsr5x+GvXiIAVCPa3ZEuRL6jMQfqfS\r\nC43mpuiS1kGgsnQLs2DbN7EFCfiJoNX1QzZu25zg+IS9PXbCJnheZWnH0rwUSb/N\r\nhZPcSefGlNlhr824OfT30v79hQnw59XbsfV270O9jPbD4kttN+OiszbU66zsuiOh\r\nBO46XCckQPqDkBMw56GPFuVrQgGb1thXvn67URJgPyJhwauBWKPNAJ9Ojuo+yVq/\r\nhdR1VNWThXQbZgaGSWrbjt6FdYtQb9VX88uu5gFDmr180HogHNUDUcqNLLdnjfFs\r\n4DyJlusQ5I/a7cQ7nlkNgxAmHszwO/mGLBuGljDUYkwZDW9nqP1Q5Q2jMtrhgXvR\r\n2SOtufvecUbB7+eoRSaOnu7CNMATG6LocFEMzhKUde1uZTfWSqnYEcdqoFJMi46y\r\nqaNxhiNLsQ5OBMbgSp2zCbQxRBdITMVvBR5YjCetUIGEs6T1yQ5wh5Xpoi34ShHn\r\nv38=\r\n=kFlZ\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n != , E:The list of sources could not be read.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
changed: [web1]

TASK [Add PPA for Apache 2.x] **************************************************
changed: [web1]

PLAY RECAP *********************************************************************
web1                       : ok=14   changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
web2                       : ok=12   changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Build step 'Execute shell' marked build as failure
Finished: FAILURE
